apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easy-polls-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/polls
            pathType: Prefix
            backend:
              service:
                name: poll-service
                port:
                  number: 8080
          - path: /api/results
            pathType: Prefix
            backend:
              service:
                name: results-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
